### ISSUE TITLE
PCBs in Germany

### ISSUE THREAD

**Issue by Sebbb** [Jan--Henrik/PD-Injector#4]
Hey,

not really an issue, but I would not know where else to put it:

I ordered a bunch of these PCBs , and ordering 30 cost almost the same as ordering 2.

So I have some left, which I would sell at my cost: 2€ for 2 pieces including shipping, or 1€ when picking up in Cologne (only the PCB, without connectors).

I soldered one, works perfectly.

Sebastian

![pcb](https://user-images.githubusercontent.com/4967941/235304077-650675ed-927c-418f-bdb0-287fc57b2862.jpg)

**Comment by PerryRhodan005** [comment]
Hi, I live in germany, though not near cologne but would be very happy if you could send me two of them for 2€ if they are still available.
Fabian

**Comment by Sebbb** [comment]
Hi,

I still have almost all of them available :)

I guess the easiest is to send me a mail, [removed, all PCBs sold]

If you attend CCC-related events, I'm at GPN and hopefully the Camp this year, so that could also be a possibility to hand over pcbs.

BTW, I found https://www.aliexpress.com/item/4001035119423.html (model F) a cheap source for matching connectors.

Sebastian

**Comment by mateusz1807** [comment]
Hi

Could you ship to Poland and with usb connectors already soldered on? How much would it cost?

**Comment by Sebbb** [comment]
Hey, sorry, no. I hate soldering those small connectors :D
